// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDreFmcu4G1QwZzJKbL3rXcEhXUZuOjbY',
    appId: '1:592235860085:web:f60358e661440b8ca3683c',
    messagingSenderId: '592235860085',
    projectId: 'charecter-ai',
    authDomain: 'charecter-ai.firebaseapp.com',
    storageBucket: 'charecter-ai.appspot.com',
    measurementId: 'G-J6E0LRG3XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ptxilHSMTPH1WOe4KVnmW3i0dUpVcPA',
    appId: '1:592235860085:android:9ec4b4afc7322745a3683c',
    messagingSenderId: '592235860085',
    projectId: 'charecter-ai',
    storageBucket: 'charecter-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDykGhUXaKRU2R2tqyaBtWgPVA4Tlbu9v0',
    appId: '1:592235860085:ios:4043f17ce8d39f8da3683c',
    messagingSenderId: '592235860085',
    projectId: 'charecter-ai',
    storageBucket: 'charecter-ai.appspot.com',
    iosBundleId: 'character.avatar.ai.app.novax',
  );
}
